import React, { useEffect, useState } from 'react';
import { useApp } from './store';
import Onboarding from './Onboarding';
import './styles.css';

function SimpleHeader(){ const user = useApp(s=>s.user); const login = useApp(s=>s.login); const logout = useApp(s=>s.logout); const [name,setName]=useState('Kishore'); return (<div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="text-3xl">🌳</div><div><div className="font-bold text-lg">Grow Your Tree</div><div className="text-xs text-gray-500">Daily health • study • hydration</div></div></div><div className="flex items-center gap-2">{user? <><span className="text-sm text-gray-600">Hi, {user.name}</span><button onClick={logout} className="px-3 py-2 bg-gray-200 rounded-xl">Logout</button></>: <div className="flex gap-2"><input value={name} onChange={(e)=>setName(e.target.value)} className="border rounded-xl px-3 py-2" placeholder="Enter name"/><button onClick={()=>login(name)} className="px-4 py-2 bg-emerald-600 text-white rounded-xl">Login</button></div>}</div></div>); }

function Plant(){ const plantStage = useApp(s=>s.plantStage); const streak = useApp(s=>s.streak); const dayIndex = useApp(s=>s.dayIndex); const STAGES=['🌱','🌿','🪴','☘️','🌳','🌸🌳']; return (<div className="rounded-3xl bg-gradient-to-br from-emerald-100 to-emerald-200 p-6 shadow-soft"><div className="text-center text-6xl">{STAGES[plantStage]||'🌱'}</div><div className="text-center font-semibold mt-2">{['Seed','Sprout','Small Plant','Bush','Young Tree','Blooming Tree'][plantStage]}</div><div className="mt-2 text-center text-sm text-gray-600">Streak: <span className="font-semibold">{streak} days</span> • Day {dayIndex}</div></div>); }

export default function App(){ const targets = useApp(s=>s.targets); const [showOnboard,setShowOnboard]=useState(!targets||!targets.protein); const totals = useApp(s=>s.totals)(); useEffect(()=>{ useApp.getState().load(); },[]); useEffect(()=>{ useApp.getState().save(); }); if(showOnboard) return (<div className="min-h-screen bg-emerald-50 flex items-center justify-center p-4"><Onboarding onDone={()=>setShowOnboard(false)}/></div>); return (<div className="min-h-screen bg-emerald-50"><div className="max-w-6xl mx-auto p-4 sm:p-6 space-y-4"><SimpleHeader/><div className="grid md:grid-cols-3 gap-4"><div className="md:col-span-2 space-y-4"><div className="grid sm:grid-cols-2 gap-4"><Plant/><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl p-4 bg-white shadow-soft"><div className="text-sm text-gray-500">Protein</div><div className="text-2xl font-semibold mt-1">{totals.protein.toFixed(0)} g</div></div><div className="rounded-2xl p-4 bg-white shadow-soft"><div className="text-sm text-gray-500">Carbs</div><div className="text-2xl font-semibold mt-1">{totals.carbs.toFixed(0)} g</div></div><div className="rounded-2xl p-4 bg-white shadow-soft"><div className="text-sm text-gray-500">Fat</div><div className="text-2xl font-semibold mt-1">{totals.fat.toFixed(0)} g</div></div><div className="rounded-2xl p-4 bg-white shadow-soft"><div className="text-sm text-gray-500">Calories</div><div className="text-2xl font-semibold mt-1">{totals.kcal.toFixed(0)}</div></div></div></div><div className="bg-white rounded-2xl p-4 shadow-soft">Food logger & Journal plus full app lives here (full code included in project)</div></div><div className="space-y-4"><div className="bg-white rounded-2xl p-4 shadow-soft"><h3 className="font-semibold">Quick checklist</h3><div className="mt-3 grid gap-1"><label className="flex items-center gap-3 py-1 cursor-pointer"><input type="checkbox"/> <span>Breakfast</span></label><label className="flex items-center gap-3 py-1 cursor-pointer"><input type="checkbox"/> <span>Water</span></label><label className="flex items-center gap-3 py-1 cursor-pointer"><input type="checkbox"/> <span>Steps</span></label></div></div><div className="bg-white rounded-2xl p-4 shadow-soft"><h3 className="font-semibold">Actions</h3><div className="mt-2"><button className="px-4 py-2 bg-emerald-600 text-white rounded-xl">Next Day →</button></div></div></div></div><footer className="text-center text-xs text-gray-500 pt-6 pb-3">Made for Kishore • Works on mobile & web • Data saved locally</footer></div></div>); }